### ISSUE TITLE
Since 1.29 version of kubernetes-control-plane there is no kube-api-endpoint relation

### ISSUE THREAD

**Issue by rgildein** [canonical/charm-openstack-service-checks#162]
Since `1.29` version of kubernetes-control-plane there is no kube-api-endpoint relation, so this charm will not work with it.

To support it, we can use `kube-control` and api-endpoints parameter, e.g. `api-endpoints: '["https://10.205.200.208:6443"]'`.

**Comment by aieri** [comment]
this issue belongs to kubernetes-service-checks (which is now deprecated). Closing
